[workspace]
authors = ["Peter Reschenhofer <peter@abteil.org>"]
channels = ["conda-forge"]
description = "Codebase for data wrangling and analyis of https://energie.wifo.ac.at"
name = "explore"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
#load-data = "Rscript load/_run-all.r"
export-data = "Rscript export/data/_run-all.r"

[dependencies]
pyyaml = ">=6.0.3,<7"

numpy = ">=2.5.3,<3"
pandas = ">=3.0.6,<4"
cdsapi = ">=0.7.7,<0.8"
xarray = ">=2026.7.0,<2027"
pip = ">=26.2.1,<27"
python = ">=3.12.14,<3.13"

r-base = ">=4.5.3,<4.6"
r-devtools = ">=2.5.2,<3"
"r-data.table" = ">=1.18.6.1,<2"
r-zoo = ">=1.9_0,<2"
r-tidyverse = ">=2.0.0,<3"
r-jsonlite = ">=2.0.0,<3"
r-xml2 = ">=1.6.0,<2"
r-httr = ">=1.4.9,<2"
r-clock = ">=0.7.4,<0.8"
r-librarian = ">=1.8.1,<2"
rsync = ">=3.4.4,<4"
r-readods = ">=2.3.6,<3"
r-arrow = ">=25.0.0,<26"
r-logger = ">=0.4.3,<0.5"
