[project]
authors = ["Peter Reschenhofer <peter@abteil.org>"]
channels = ["conda-forge"]
description = "Codebase for data wrangling and analyis of https://energie.wifo.ac.at"
name = "explore"
platforms = ["linux-64"]
version = "0.1.0"

[tasks]
#load-data = "Rscript load/_run-all.r"
sync-data = "./sync-storage.sh"
export-data = "Rscript export/data/_run-all.r"

sync-export-data = { depends-on = ["sync-data", "export-data"] }

[dependencies]
pyyaml = ">=6.0.2,<7"
r-base = ">=4.4.2,<4.5"
numpy = ">=2.2.0,<3"
pandas = ">=2.2.3,<3"
cdsapi = ">=0.7.5,<0.8"
xarray = ">=2024.11.0,<2025"
pip = ">=24.3.1,<25"
python = ">=3.12.8,<3.13"
r-devtools = ">=2.4.5,<3"
"r-data.table" = ">=1.15.4,<2"
r-zoo = ">=1.8_12,<2"
r-tidyverse = ">=2.0.0,<3"
r-jsonlite = ">=1.8.9,<2"
r-googledrive = ">=2.1.1,<3"
r-xml2 = ">=1.3.6,<2"
r-httr = ">=1.4.7,<2"
r-clock = ">=0.7.1,<0.8"
r-librarian = ">=1.8.1,<2"
rsync = ">=3.3.0,<4"
